version: '3'

services:
  app:
    build: ./go/
    volumes:
      - ./go:/go/src

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./src:/usr/share/nginx/html

  mysql:
    image: mysql:latest
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "fullcycle"
    
  